# Generated by Django 3.2.8 on 2021-10-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uesr',
            new_name='User',
        ),
    ]
