# Generated by Django 3.2.7 on 2021-10-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20211003_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='书名')),
                ('pub', models.CharField(default='', max_length=100, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='价格')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='市场价')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
